"""Tools for https on localhost.

Since companies may want to host ComfyUI over TLS (https),
we need to make sure that the browser can establish a client connection
to our WSRPC server endpoint on localhost.
To do that, we need a Certificate Authority to be installed for:
localhost, 127.0.0.1, and ::1, to cover hostname, ipv4 and ipv6,
This is a bit dangerous, in rpc_server we check the Origin header.

We make use of 'mkcert' to generate these certificates and install the root CA.
This can is done locally, on a user level.
Each root CA generated by mkcert is UNIQUE PER PC / ACCOUNT.

TODO(@sas): Add HMAC Challenge (or not. It appears that it might not matter.)

Additionally, a thing to keep in mind is that while the browser uses
the OS' CA store, SSL has it's own stores, therefore we need to append the
one generated by mkcert to SSLs stores at runtime.
"""

from __future__ import annotations

import logging
import os
import secrets
import ssl
import subprocess
import sys
from pathlib import Path

from ayon_comfyui.api.util import cache_result
from ayon_comfyui.parse_settings import ComfyRemoteSettings

# TODO(@sas): Clean this up once testing is no longer needed
if __name__ != "__main__":
    from ayon_comfyui.api.consts import LOG_LEVEL

    logging.basicConfig(force=True, stream=sys.stdout, level=LOG_LEVEL)
    log = logging.getLogger("ayon_comfyui")
else:
    LOG_LEVEL = logging.DEBUG

    logging.basicConfig(force=True, stream=sys.stdout, level=LOG_LEVEL)
    log = logging.getLogger()

CERTS_FOLDER = Path(__file__).parent.parent.parent / "certs"


def get_mkcert_executable() -> Path | None:
    """Return path to mkcert based on settings.

    Fall back to environment variable MKCERT_PATH.
    """
    settings, _ = ComfyRemoteSettings.pull_committed_settings()

    if (
        isinstance(settings, ComfyRemoteSettings)
        and settings.mkcert_executable
    ):
        return Path(settings.mkcert_executable)

    path = os.environ.get("MKCERT_PATH", None)
    if path is not None:
        return Path(path)

    return None


def get_comfyui_cert_key() -> tuple[Path, Path]:
    """Returns a tuple of paths containing certificate and key."""
    return (
        CERTS_FOLDER / "comfyui-cert.crt",
        CERTS_FOLDER / "comfyui-key.key",
    )


def comfyui_cert_key_exists() -> bool:
    """Return True if expected cert / key exists."""
    return all(crt.exists() for crt in get_comfyui_cert_key())


def mkcert_install() -> None:
    """Install mkcert.

    Raises:
        FileNotFoundError: if mkcert executable couldn't be found.
    """
    if (exec_ := get_mkcert_executable()) is None:
        raise FileNotFoundError("Couldn't find mkcert executable")  # noqa: EM101

    proc = subprocess.Popen(
        [exec_, "-install"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
        errors="ignore",
    )
    _, out = proc.communicate()
    # The local CA is already installed in the system trust store!
    if "already installed" in out.strip():
        log.info("mkcert CA already installed!")
    elif "now installed" in out.strip():
        log.info("mkcert CA installed!")


def mkcert_uninstall() -> None:
    """Uninstall mkcert.

    Raises:
        FileNotFoundError: if mkcert executable couldn't be found.
    """
    if (exec_ := get_mkcert_executable()) is None:
        raise FileNotFoundError("Couldn't find mkcert executable")  # noqa: EM101

    proc = subprocess.Popen(
        [exec_, "-uninstall"], stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    proc.wait()


def mkcert_generate_keys() -> None:
    """Use mkcert to generate keys.

    Raises:
        FileNotFoundError: if mkcert executable couldn't be found.
    """
    if (exec_ := get_mkcert_executable()) is None:
        raise FileNotFoundError("Couldn't find mkcert executable")  # noqa: EM101

    args = [
        exec_,
        "-cert-file",
        "comfyui-cert.crt",
        "-key-file",
        "comfyui-key.key",
        "localhost",
        "127.0.0.1",
        # "::1", we're not hosting on ipv6 lets be real
    ]

    proc = subprocess.Popen(
        args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=CERTS_FOLDER
    )
    proc.wait()


def get_ssl_context_client() -> ssl.SSLContext:
    """Deduce CA location and make a context for it.

    SSL does not natively trust any licenses generated with
    CA authorities that aren't native to SSL.

    Returns:
        Client suitable SSL context.
    """
    exec_ = get_mkcert_executable()

    if exec_ is None:
        # if no absolute path can be found, attempt
        exec_ = "mkcert"

    try:
        proc = subprocess.Popen(
            [exec_, "-CAROOT"],
            stdout=subprocess.PIPE,
            text=True,
        )
    except FileNotFoundError:
        # mkcert not found in PATH
        return None

    out, _ = proc.communicate()

    if not out.strip():
        # Somehow, printed nothing but returned 0
        return None

    # Default name.
    ca_loc = Path(out.strip()) / "rootCA.pem"

    ssl_context = ssl.create_default_context()
    ssl_context.load_verify_locations(ca_loc)
    return ssl_context


def get_ssl_context_server() -> ssl.SSLContext:
    """Returns an ssl context used for Servers."""
    cert, key = get_comfyui_cert_key()
    ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    ssl_context.load_cert_chain(cert, key)
    return ssl_context


class MkcertContext:
    """Manager for temporary keys and root certificate.

    Generates a fresh sets of keys and installs mkcert CA into
    trusted root certificates.

    This will be uninstalled on exit.

    ```
    with MkcertContext() as (ssl_server_ctx, ssl_client_ctx):
        ...
    ```
    """

    def __init__(self) -> None:
        """Manager for temporary keys and root certificate.

        Generates a fresh sets of keys and installs mkcert CA into
        trusted root certificates.

        This will be uninstalled on exit.

        ```
        with MkcertContext() as (ssl_server_ctx, ssl_client_ctx):
            ...
        ```
        """
        settings, profile = ComfyRemoteSettings.pull_committed_settings()
        self.https = profile.is_https
        self.uninit_at_exit = settings.mkcert_uninstall_at_exit

    def __enter__(self) -> tuple[ssl.SSLContext, ssl.SSLContext]:
        """Return serverside and clienside SSL context.

        Generates a fresh sets of keys and installs mkcert CA into
        trusted root certificates.

        This will be uninstalled on exit.

        ```
        with MkcertContext() as (ssl_server_ctx, ssl_client_ctx):
            ...
        ```
        """
        if self.https:
            mkcert_install()
            mkcert_generate_keys()
            return (get_ssl_context_server(), get_ssl_context_client())
        return (None, None)

    def __exit__(self, *args: object) -> None:
        """Return nothing.

        Exit mkcert context and uninitialize (if needed)
        """
        if self.uninit_at_exit and self.https:
            mkcert_uninstall()


@cache_result
def get_session_secret() -> str:
    """Returns a 16 char long hex-compatible secret.

    This function is cached and will reproduce the same output.
    """
    return secrets.token_hex(16)


if __name__ == "__main__":
    os.environ["MKCERT_PATH"] = (
        R"C:\Users\sas.vangulik\Documents\mkcert\mkcert.exe"
    )
    mkcert_install()
    mkcert_generate_keys()
    log.info(comfyui_cert_key_exists())
    log.info(get_ssl_context_client())
    mkcert_uninstall()

    with MkcertContext() as (srv, cli):
        pass
